---

# This is a collection of monitors to check various states at regular scheduled intervals.
# Monitors performed:
#  Check for bids last 15 minutes
#  Check docker container "otnode" is running every 5 minutes

# Settings to edit:
# All "bidcheck_" entries
# All "dockercheck_" entries

- name: Install Monitors
  hosts: all
  vars:
    bidcheck_minute: '*/15' # Checks every 15 minutes
    bidcheck_hour: '*'
    bidcheck_day: '*'
    bidcheck_month: '*'
    bidcheck_weekday: '*'
    dockercheck_minute: '*/5' # Checks every 5 minutes
    dockercheck_hour: '*'
    dockercheck_day: '*'
    dockercheck_month: '*'
    dockercheck_weekday: '*'
  gather_facts: no

  tasks:
    - name: Clone OT-NodeWatch git repository
      git:
        repo: 'https://github.com/calr0x/OT-NodeWatch.git'
        dest: /root/OT-NodeWatch
        force: yes

    - name: Install config.sh
      copy:
        src: ~/OT-NodeWatch/config.sh
        dest: /root/OT-NodeWatch/config.sh
        owner: root
        group: root
        mode: '0600'

    - name: Delete existing monitor (bid check) schedule from cron
      cron:
        name: Monitor Bid Check
        state: absent

    - name: Add monitor (bid check) schedule to cron (every 15 minutes)
      cron:
        name: Monitor Bid Check
        minute: "{{ bidcheck_minute }}"
        hour: "{{ bidcheck_hour }}"
        day: "{{ bidcheck_day }}"
        month: "{{ bidcheck_month }}"
        weekday: "{{ bidcheck_weekday }}"
        job: "/root/OT-NodeWatch/bid_check/bid_check.sh"

    - name: Delete existing monitor (docker check) schedule from cron
      cron:
        name: Monitor Docker Check
        state: absent

    - name: Add monitor (Docker check) schedule to cron (every 5 minutes)
      cron:
        name: Monitor Docker Check
        minute: "{{ dockercheck_minute }}"
        hour: "{{ dockercheck_hour }}"
        day: "{{ dockercheck_day }}"
        month: "{{ dockercheck_month }}"
        weekday: "{{ dockercheck_weekday }}"
        job: "/root/OT-NodeWatch/docker_check/docker_check.sh"
